### ISSUE TITLE
Add a database volume to docker-compose file

### ISSUE THREAD

**Issue by oDeano** [sveltejs/cli#194]
When adding drizzle, the [adder creates a compose file for the db](https://github.com/sveltejs/cli/blob/65981de024f74b5bb57542b26d01286c7df3b537/packages/adders/drizzle/index.ts#L130) but doesn't add a volume to persist the data, is it worthwhile to add it to the template?

```
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
```
